// Gerado por `npm run errors:export` no allervia-backend. Não edite à mão.

export interface ErrorCatalogEntry {
  code: string
  status: number
  message: string
}

export const ERROR_CATALOG: readonly ErrorCatalogEntry[] = [
  { code: 'ADJUSTMENT_REASON_REQUIRED', status: 400, message: "Informe o motivo do ajuste da dose." },
  { code: 'ADMINISTRATION_BEFORE_INDUCTION_START', status: 409, message: "A data e hora da administração são anteriores ao início do tratamento." },
  { code: 'ADMINISTRATION_IN_FUTURE', status: 400, message: "A data e hora da administração não podem estar no futuro." },
  { code: 'ADMINISTRATION_OUT_OF_ORDER', status: 409, message: "Já existe uma dose registrada com data e hora posteriores a esta. Registre as doses em ordem." },
  { code: 'APPOINTMENT_ALREADY_CLOSED', status: 409, message: "Este agendamento já foi encerrado e não pode mais ser alterado." },
  { code: 'AUTOMATION_DISABLED', status: 409, message: "A automação de protocolos está desativada para esta clínica. Fale com quem administra a conta." },
  { code: 'BAD_REQUEST', status: 400, message: "Requisição inválida." },
  { code: 'CLINICAL_AUTHOR_REQUIRED', status: 403, message: "Apenas médicos podem realizar esta ação." },
  { code: 'CLINICAL_TRANSITION_REVIEW_REQUIRED', status: 400, message: "Este protocolo exige revisão clínica antes de ser usado." },
  { code: 'CONCENTRATION_OUTSIDE_STORAGE_RANGE', status: 400, message: "Concentração fora do intervalo aceito. Revise o valor informado." },
  { code: 'CONDUCT_JUSTIFICATION_REQUIRED', status: 400, message: "Informe a justificativa da conduta escolhida." },
  { code: 'CONDUCT_REQUIRES_PHYSICIAN', status: 403, message: "Apenas médicos podem registrar esta conduta." },
  { code: 'CONFLICT', status: 409, message: "A operação conflita com o estado atual do registro." },
  { code: 'DOSE_ALREADY_SCHEDULED', status: 409, message: "Esta dose já possui um agendamento ativo." },
  { code: 'DOSE_APPOINTMENT_REQUIRES_REVIEW', status: 409, message: "Esta dose já teve um agendamento encerrado. Revise o histórico antes de agendar de novo." },
  { code: 'DOSE_NOT_ADMINISTERED', status: 409, message: "Esta dose ainda não foi administrada." },
  { code: 'DOSE_NOT_SCHEDULED', status: 409, message: "Esta dose não está agendada e não pode ser alterada." },
  { code: 'DOSE_VALUES_REQUIRED', status: 400, message: "Informe os valores da dose." },
  { code: 'DUPLICATE_OBSERVATION_PHASE', status: 400, message: "Já existe uma observação registrada para esta fase. Use apenas uma por fase." },
  { code: 'ENDPOINT_RETIRED', status: 410, message: "Este recurso foi descontinuado. Atualize o aplicativo." },
  { code: 'FORBIDDEN', status: 403, message: "Você não tem permissão para esta ação." },
  { code: 'GUARDIAN_NOT_ALLOWED_FOR_ADULT', status: 400, message: "Paciente maior de idade não tem responsável legal. Remova os dados do responsável." },
  { code: 'GUARDIAN_REQUIRED_FOR_MINOR', status: 400, message: "Paciente menor de idade exige responsável legal. Informe nome e telefone do responsável." },
  { code: 'IDEMPOTENCY_KEY_REQUIRED', status: 400, message: "Não foi possível concluir o envio. Recarregue a página e tente de novo." },
  { code: 'IDEMPOTENCY_KEY_REUSED', status: 409, message: "Este envio já foi processado com dados diferentes. Recarregue a página e confira antes de repetir." },
  { code: 'INTERNAL_ERROR', status: 500, message: "Erro interno ao processar a requisição." },
  { code: 'INVALID_ADMINISTRATION_WINDOW', status: 400, message: "O término da administração não pode ser anterior ao início." },
  { code: 'INVALID_AS_OF', status: 400, message: "Data de referência inválida. Use uma data que não esteja no futuro." },
  { code: 'INVALID_DOSE_LINK', status: 400, message: "A dose selecionada não está disponível para agendamento deste paciente." },
  { code: 'INVALID_LIFECYCLE_TRANSITION', status: 409, message: "Esta mudança de situação não é permitida a partir do estado atual do tratamento." },
  { code: 'INVALID_OBSERVATION_TIME', status: 400, message: "Horário da observação inválido. Deve ser posterior à administração e não pode estar no futuro." },
  { code: 'INVALID_PERIOD', status: 400, message: "Período inválido. A data inicial deve ser anterior à final." },
  { code: 'INVALID_TIME_ZONE', status: 400, message: "Fuso horário inválido." },
  { code: 'LEGACY_TARGET_MISMATCH', status: 409, message: "O protocolo escolhido não corresponde ao alvo do tratamento atual. Escolha outra versão." },
  { code: 'METHOD_NOT_ALLOWED', status: 405, message: "Operação não permitida neste endereço." },
  { code: 'MISS_BEFORE_START', status: 409, message: "Não é possível marcar falta antes do horário do agendamento." },
  { code: 'NOT_FOUND', status: 404, message: "Registro não encontrado." },
  { code: 'PATIENT_INACTIVE', status: 409, message: "Paciente inativo. Reative o cadastro para seguir." },
  { code: 'PATIENT_NOT_FOUND', status: 404, message: "Paciente não encontrado." },
  { code: 'PATIENT_XOR_PATIENT_ID_REQUIRED', status: 400, message: "Informe um paciente já cadastrado ou os dados de um novo — não os dois." },
  { code: 'PENDING_DOSE_REQUIRES_REVIEW', status: 409, message: "O tratamento precisa ter exatamente uma dose agendada pendente para esta operação. Revise a agenda." },
  { code: 'PERFORMER_NOT_AUTHORIZED', status: 400, message: "O profissional informado não tem permissão para aplicar esta dose." },
  { code: 'PRESCRIBER_MUST_BE_RESPONSIBLE_PHYSICIAN', status: 400, message: "Ao cadastrar um novo paciente, o médico responsável deve ser você." },
  { code: 'PRESCRIPTION_ALREADY_BOUND', status: 409, message: "Este tratamento já está vinculado a uma prescrição de protocolo." },
  { code: 'PRESCRIPTION_REVISION_REQUIRED', status: 400, message: "Este campo só pode ser alterado por revisão de prescrição." },
  { code: 'PRESCRIPTION_TIME_ZONE_REQUIRED', status: 409, message: "A prescrição não tem fuso horário definido. Fale com quem administra a conta." },
  { code: 'PROTOCOL_MANAGER_REQUIRED', status: 403, message: "Apenas médicos ou administradores podem gerenciar protocolos." },
  { code: 'PROTOCOL_MIGRATION_REQUIRED', status: 409, message: "Este tratamento ainda usa o modelo antigo de protocolo. Migre para um protocolo configurável antes de seguir." },
  { code: 'PUBLISHED_DEFAULT_REQUIRED', status: 409, message: "Defina uma versão publicada como padrão para esta via de administração." },
  { code: 'PUBLISHED_PROTOCOL_NOT_FOUND', status: 404, message: "Protocolo publicado não encontrado para esta via de administração." },
  { code: 'PUBLISHED_PROTOCOL_REQUIRED', status: 409, message: "Nenhum protocolo padrão definido para esta via. Escolha uma versão ou defina um padrão." },
  { code: 'PUBLISHED_VERSION_IMMUTABLE', status: 409, message: "Versão já publicada não pode ser editada. Crie um novo rascunho." },
  { code: 'PUBLISHED_VERSION_REQUIRED', status: 409, message: "Esta ação exige uma versão publicada." },
  { code: 'RECOMMENDATIONS_ONLY_ON_COMPLETION', status: 400, message: "Recomendações só podem ser registradas ao concluir o tratamento." },
  { code: 'RESPONSIBLE_PHYSICIAN_NOT_FOUND', status: 404, message: "Médico responsável não encontrado ou inativo." },
  { code: 'RETURN_FORECAST_ONLY_ON_SUSPENSION', status: 400, message: "Previsão de retorno só pode ser informada ao suspender o tratamento." },
  { code: 'REVISION_TARGETS_SAME_VERSION', status: 409, message: "A versão escolhida já é a que está em uso. Selecione outra." },
  { code: 'SCHEDULE_REQUIRES_CALENDAR_REVIEW', status: 400, message: "Não foi possível calcular a próxima data. Revise o calendário do protocolo." },
  { code: 'SERVICE_UNAVAILABLE', status: 503, message: "Serviço temporariamente indisponível. Tente de novo em instantes." },
  { code: 'STALE_APPOINTMENT_REVISION', status: 409, message: "Este agendamento foi alterado por outra pessoa. Recarregue e tente de novo." },
  { code: 'STALE_CLINICAL_REVISION', status: 409, message: "Este registro foi alterado por outra pessoa. Recarregue e tente de novo." },
  { code: 'STALE_PROTOCOL_REVISION', status: 409, message: "Este protocolo foi alterado por outra pessoa. Recarregue e tente de novo." },
  { code: 'STATUS_REASON_REQUIRED', status: 400, message: "Informe o motivo do cancelamento ou da falta." },
  { code: 'SUCCESSOR_ALREADY_ADMINISTERED', status: 409, message: "A dose seguinte já foi administrada. Não é possível corrigir esta." },
  { code: 'TIMESTAMP_WITH_OFFSET_REQUIRED', status: 400, message: "Data e hora em formato inválido. Recarregue a página e tente de novo." },
  { code: 'TOO_MANY_ATTEMPTS', status: 429, message: "Muitas tentativas. Aguarde um instante e tente de novo." },
  { code: 'TREATMENT_NOT_ACTIVE', status: 409, message: "Este tratamento não está ativo." },
  { code: 'UNAUTHENTICATED', status: 401, message: "Sessão expirada ou inválida. Entre novamente." },
  { code: 'UNCHANGED_THERAPY_STATUS', status: 400, message: "O tratamento já está nessa situação." },
  { code: 'UNPROCESSABLE_ENTITY', status: 422, message: "Não foi possível processar os dados enviados." },
  { code: 'UNSUPPORTED_AUTOMATION_ROUTE', status: 400, message: "Via de administração ainda não suportada pela automação. Apenas subcutânea." },
  { code: 'UNSUPPORTED_CONTENT_TYPE', status: 415, message: "Formato de conteúdo não suportado." },
  { code: 'UNSUPPORTED_ROUTE', status: 409, message: "Via de administração não suportada nesta operação. Apenas subcutânea." },
  { code: 'VALIDATION_ERROR', status: 400, message: "Requisição inválida. Confira os campos destacados." },
  { code: 'VALUE_OUTSIDE_EXACT_STORAGE_RANGE', status: 400, message: "Valor fora do intervalo aceito. Revise volume, concentração e intervalo." },
]
